import { StyleSheet } from "react-native";
/* =============== Theme & helpers =============== */
const palette = {
  bg: "#F7F7FA",
  card: "#FFFFFF",
  text: "#111827",
  textDim: "#6B7280",
  line: "#E5E7EB",
  accent: "#FF2D55",
  accent2: "#2563EB",
  pill: "#F3F4F6",
};

/* =============== Styles =============== */
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.bg },

  hero: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: palette.card,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: palette.line,
  },
  brandMini: {
    color: palette.accent,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 2,
  },
  brand: {
    color: palette.text,
    fontWeight: "900",
    fontSize: 24,
    letterSpacing: 0.3,
  },
  brandSub: { color: palette.textDim, marginTop: 4, fontWeight: "600" },
  heroRow: { flexDirection: "row", gap: 10, marginTop: 12 },
  heroPicker: {
    borderWidth: 1,
    borderColor: palette.accent,
    backgroundColor: "#FFF5F7",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  heroPickerText: { color: palette.accent, fontWeight: "800", marginRight: 6 },
  heroPickerIcon: { color: palette.accent, fontWeight: "900" },

  sectionHeader: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { fontSize: 18, fontWeight: "900", color: palette.text },
  counterText: { color: palette.textDim, fontWeight: "700" },

  theaterCard: {
    backgroundColor: palette.card,
    marginHorizontal: 12,
    marginBottom: 12,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
    borderWidth: 1,
    borderColor: palette.line,
  },
  theaterImage: { width: "100%", height: 148, backgroundColor: "#EEE" },
  theaterBody: {
    flexDirection: "row",
    padding: 12,
    gap: 10,
    alignItems: "flex-start",
  },
  theaterName: { fontSize: 16, fontWeight: "900", color: palette.text },
  theaterAddr: { color: palette.textDim, marginTop: 2, fontWeight: "600" },
  amenityRow: { flexDirection: "row", gap: 6, flexWrap: "wrap", marginTop: 8 },
  amenityChip: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#fff",
  },
  amenityText: { color: palette.textDim, fontWeight: "800", fontSize: 12 },
  distanceBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#F9FAFB",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.line,
  },
  distanceIcon: { fontSize: 14 },
  distanceText: { color: palette.text, fontWeight: "900" },

  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  modalCard: {
    position: "absolute",
    left: 16,
    right: 16,
    top: 120,
    bottom: 120,
    backgroundColor: palette.card,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
    borderWidth: 1,
    borderColor: palette.line,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: palette.text,
    marginBottom: 8,
  },
  cityItem: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.line,
    marginBottom: 8,
    backgroundColor: "#fff",
  },
  cityItemActive: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  cityText: { fontWeight: "900", color: palette.text },
  cityTextActive: { color: "#fff" },
  modalCloseBtn: {
    marginTop: 8,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.accent,
    backgroundColor: "#FFF5F7",
  },
  modalCloseText: { fontWeight: "900", color: palette.accent },
});
export default styles;
